spring:
  application:
    name: spring-cloud-netflix-consumer

server:
  port: 8764

swagger:
  base:
    package: com.framework.consumer.controller

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/