spring:
  application:
    name: spring-cloud-netflix-config
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://git.lug.ustc.edu.cn/KwonJiYong/spring-cloud-config.git
          search-paths: respo
          username: 918513194@qq.com
          password: 136518XFY

server:
  port: 8888  # 默认是8888  在application.yml里面改不了   只能在bootstrap.yml里面改

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/