spring:
  application:
    name: spring-cloud-netflix-provider
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8762

swagger:
  base:
    package: com.framework.provider.controller

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/